### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by MarkoPielic** [pusher/pusher-websocket-dotnet#119]
I'm getting ArgumentNullException when using pusher .net client in C# and it causes my application to crash.
Is there any thing I can do to prevent this? The stack trace is below.

System.ArgumentNullException: Value cannot be null.
Parameter name: obj
   at System.Threading.Monitor.Pulse(Object obj)
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at PusherClient.Connection.RaiseError(PusherException error)
   at PusherClient.Connection.WebsocketError(Object sender, ErrorEventArgs e)
   at WebSocket4Net.WebSocket.client_Error(Object sender, ErrorEventArgs e)
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Dns.ResolveCallback(Object context)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by lisarost** [comment]
@MarkoPielic should we reach out to the user again after the latest release?
