### ISSUE TITLE
Unable to save excel file with pictures.

### ISSUE THREAD

**Issue by Mani1782000** [pusher/pusher-websocket-dotnet#147]
I am using epplus 6.2.6. I am getting the below error while saving excel which contains picture in it.

System.InvalidOperationException: Error saving file ${file} ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, ExcelGroupShape shape)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawingFromNode(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)
   at OfficeOpenXml.ExcelWorksheet.SaveDrawings()
   at OfficeOpenXml.ExcelWorksheet.Save()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.Save()
   --- End of inner exception stack trace ---
   at OfficeOpenXml.ExcelPackage.Save()
   at dummy2.Code1(String image, String file, Boolean& success, String& message)

**Comment by benw-pusher** [comment]
I don't believe this issue relates to this library so I will close it. Please raise a new issue with more information if this does relate to our library.
