### ISSUE TITLE
websocket_MessageReceived() Unhandled Exception

### ISSUE THREAD

**Issue by guypld** [pusher/pusher-websocket-dotnet#41]
Hi,

In **PusherClient/Connection.cs** , at:
**_websocket_MessageReceived(object sender, MessageReceivedEventArgs e)_**

there's no exception handling, and because it happens on different thread - one exception can crash the application!

This is the exception I got:

_System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PusherClient.EventEmitter.EmitEvent(String eventName, String data)
   at PusherClient.Connection.websocket_MessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)_

So I think the best way to cover those errors is to catch this at this function.

What do you think?
Thanks.

**Comment by Boogier** [comment]
It would be better to use thread safe collections or syncronization locks. So such an error would never happen at all.

**Comment by damdo** [comment]
#93 has introduced concurrent collections in the `EventEmitter` to avoid race conditions, and the reported issue should now be fixed.

**Comment by damdo** [comment]
Similar issue: https://github.com/pusher/pusher-websocket-dotnet/issues/76
